name: apsim-wofost-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - xgboost
  - shap
  - scipy
  - statsmodels
  - pip
  - pip:
      - SALib
      - pcse